apiVersion: apps/v1
kind: Deployment
metadata:
 name: nodejs-backend-deployment
 labels:
   app: nodejs-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-backend-app
  template:
    metadata:
      labels:
        app: nodejs-backend-app
    spec:
      containers:
        - name: backend-server
          image: patrick358/simple_node_application:backend
          ports:
            - containerPort: 1234
      # nodeSelector:
      #   service: backend