apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/patrickgatiri/ArgoCD-Deployment.git
    targetRevision: HEAD
    path: manifests/persistence/consul-helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false