apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-application
spec:
  selector:
    matchLabels:
      run: simple-node-application
  replicas: 2
  template:
    metadata:
      labels:
        run: simple-node-application
    spec:
      containers:
      - name: simple-node-application-client-side
        image: patrick358/simple_node_application:client-side
        ports:
        - containerPort: 1234
      - name: simple-node-application-server-side
        image: patrick358/simple_node_application:server-side
        ports:
        - containerPort: 3000
