operator:
  image:
    name: ghcr.io/borchero/meerkat/operator
    tag: ${CIRCLE_TAG}
  debug: false

ovpn:
  image:
    name: ghcr.io/borchero/meerkat/server
    tag: ${CIRCLE_TAG}

vault:
  address: http://vault.security.svc.kubernetes
  # Vault is configured not to use TLS
  # caCrt: ~
  pkiPath: meerkat
  auth:
    type: kubernetes
    mountPath: auth/kubernetes
    config:
      role: openvpn-server
  agent:
    image: 
      name: vault
      tag: 1.6.2

rbac:
  serviceAccountName: ~
