apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/patrickgatiri/NodeJS-Deployment.git
    targetRevision: HEAD
    path: manifests/backend/nodejs-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true