apiVersion: apps/v1
 kind: Deployment
 metadata:
  name: nodejs-backend
  labels:
    app: nodejs-backend
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: nodejs-backend
    template:
      metadata:
        labels:
          app: nodejs-backend
      spec:
        containers:
          - name: backend-server
            image: patrick358/simple_node_application
            ports:
              - containerPort: 88