apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/patrickgatiri/NodeJS-Deployment.git
    targetRevision: HEAD
    path: manifests/security/vault-helm
    helm:
      valueFiles:
        - override-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true